# Generated by Django 3.2.4 on 2021-06-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210624_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='author',
        ),
        migrations.AddField(
            model_name='homepage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat', to='home.author'),
        ),
    ]
